import Head from "next/head";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Proxy Youtube Docs</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="https://www.google.com/s2/favicons?sz=64&domain=https://youtube.com/" />
            </Head>
            <main className={inter.className}>
                <h1>What is This?</h1>
                <p>Proxy Youtube is a web app that allows you to watch YouTube videos without ads.</p>
                <h2>How to Use</h2>
                <p>Enter the YouTube URL in the input field and click the "Proxy" button to watch the video without ads.</p>
                <h2>What is not same between Proxy and Without Proxy</h2>
                <p>Proxy is using One server and bypass block youtube.</p>
                <p>Without Proxy is using your browser and you can't bypass block youtube.and Can control.</p>
                <p>Proxy is using Stream.so you can't control video.</p>
            </main>
        </>
    );
}
