import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

function findID(url: string): string | null {
  var regExp = /^.*((youtu.be\/)|(v\/)|(\/u\/\w\/)|(embed\/)|(watch\?))\??v?=?([^#&?]*).*/;
  var match = url.match(regExp);
  console.log((match && match[7].length == 11) ? match[7] : null);
  return (match && match[7].length == 11) ? match[7] : null;
}

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const handleNoProxy = async (id: string | null) => {
    if(!id) return;
    fetch(`/api/i/${id}`)
    .then(res => res.json())
    .then(data => {
      document.getElementsByTagName("video")[1].src = data.videoFull;
    });
  }

  return (
    <>
      <Head>
        <title>Proxy Youtube</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://www.google.com/s2/favicons?sz=64&domain=https://youtube.com/" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1 className={styles.title}>Proxy Youtube</h1>
        <p className={styles.description}>Proxy Youtube is a web app that allows you to watch YouTube videos without ads.</p>
        <div className={styles.form}>
          <div>
            <input type="text" placeholder="Enter YouTube URL" />
            <button onClick={() => document.getElementsByTagName("video")[0].src = `/api/v/${findID(document.getElementsByTagName("input")[0].value) ? findID(document.getElementsByTagName("input")[0].value) : "WIRK_pGdIdA"}`}>Proxy</button>
          </div>
          <video autoPlay controls></video>
        </div>
        <h2>Without Proxy</h2>
        <div className={styles.form}>
          <div>
            <input type="text" placeholder="Enter YouTube URL" />
            <button onClick={() => handleNoProxy(findID(document.getElementsByTagName("input")[1].value) ? findID(document.getElementsByTagName("input")[1].value) : "WIRK_pGdIdA")}>Proxy</button>
          </div>
          <video autoPlay controls></video>
        </div>
      </main>
    </>
  );
}
